export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const REFRESH_CATEGORIES_START = 'REFRESH_CATEGORIES_START';
export const REFRESH_CATEGORIES = 'REFRESH_CATEGORIES';
export const REFRESH_CATEGORIES_ERROR = 'REFRESH_CATEGORIES_ERROR';
