export const GET_RESTAURANTS_START = 'GET_RESTAURANTS_START';
export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const GET_RESTAURANTS_ERROR = 'GET_RESTAURANTS_ERROR';

export const REFRESH_RESTAURANTS_START = 'REFRESH_RESTAURANTS_START';
export const REFRESH_RESTAURANTS = 'REFRESH_RESTAURANTS';
export const REFRESH_RESTAURANTS_ERROR = 'REFRESH_RESTAURANTS_ERROR';
