export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS = 'GET_USERS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const REFRESH_USERS_START = 'REFRESH_USERS_START';
export const REFRESH_USERS = 'REFRESH_USERS';
export const REFRESH_USERS_ERROR = 'REFRESH_USERS_ERROR';
