export const EDIT_PROFILE_START = 'EDIT_PROFILE_START';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';

export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const REFRESH_PROFILE_START = 'REFRESH_PROFILE_START';
export const REFRESH_PROFILE = 'REFRESH_PROFILE';
export const REFRESH_PROFILE_ERROR = 'REFRESH_PROFILE_ERROR';

export const DELETE_PROFILE_START = 'DELETE_PROFILE_START';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const DELETE_PROFILE_ERROR = 'DELETE_PROFILE_ERROR';
