export const GET_CATEGORY_START = 'GET_CATEGORY_START';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';

export const REFRESH_CATEGORY_START = 'REFRESH_CATEGORY_START';
export const REFRESH_CATEGORY = 'REFRESH_CATEGORY';
export const REFRESH_CATEGORY_ERROR = 'REFRESH_CATEGORY_ERROR';

export const ADD_CATEGORY_START = 'ADD_CATEGORY_START';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR';

export const EDIT_CATEGORY_START = 'EDIT_CATEGORY_START';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const EDIT_CATEGORY_ERROR = 'EDIT_CATEGORY_ERROR';

export const DELETE_CATEGORY_START = 'DELETE_CATEGORY_START';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';
