export const GET_REVIEW_START = 'GET_REVIEW_START';
export const GET_REVIEW = 'GET_REVIEW';
export const GET_REVIEW_ERROR = 'GET_REVIEW_ERROR';

export const REFRESH_REVIEW_START = 'REFRESH_REVIEW_START';
export const REFRESH_REVIEW = 'REFRESH_REVIEW';
export const REFRESH_REVIEW_ERROR = 'REFRESH_REVIEW_ERROR';

export const ADD_REVIEW_START = 'ADD_REVIEW_START';
export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_ERROR = 'ADD_REVIEW_ERROR';

export const EDIT_REVIEW_START = 'EDIT_REVIEW_START';
export const EDIT_REVIEW = 'EDIT_REVIEW';
export const EDIT_REVIEW_ERROR = 'EDIT_REVIEW_ERROR';

export const DELETE_REVIEW_START = 'DELETE_REVIEW_START';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const DELETE_REVIEW_ERROR = 'DELETE_REVIEW_ERROR';
