export const GET_RESTAURANT_START = 'GET_RESTAURANT_START';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const GET_RESTAURANT_ERROR = 'GET_RESTAURANT_ERROR';

export const REFRESH_RESTAURANT_START = 'REFRESH_RESTAURANT_START';
export const REFRESH_RESTAURANT = 'REFRESH_RESTAURANT';
export const REFRESH_RESTAURANT_ERROR = 'REFRESH_RESTAURANT_ERROR';

export const ADD_RESTAURANT_START = 'ADD_RESTAURANT_START';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const ADD_RESTAURANT_ERROR = 'ADD_RESTAURANT_ERROR';

export const EDIT_RESTAURANT_START = 'EDIT_RESTAURANT_START';
export const EDIT_RESTAURANT = 'EDIT_RESTAURANT';
export const EDIT_RESTAURANT_ERROR = 'EDIT_RESTAURANT_ERROR';

export const DELETE_RESTAURANT_START = 'DELETE_RESTAURANT_START';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const DELETE_RESTAURANT_ERROR = 'DELETE_RESTAURANT_ERROR';
