export const GET_REVIEWS_START = 'GET_REVIEWS_START';
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR';

export const REFRESH_REVIEWS_START = 'REFRESH_REVIEWS_START';
export const REFRESH_REVIEWS = 'REFRESH_REVIEWS';
export const REFRESH_REVIEWS_ERROR = 'REFRESH_REVIEWS_ERROR';
